export enum ChartZones {
  TITLE_BAR = 'TITLE_BAR',
  Y_AXIS_TITLE = 'Y_AXIS_TITLE',
  X_AXIS_TITLE = 'X_AXIS_TITLE',
  CHART_PLOT_BASE = 'CHART_PLOT_BASE',
  CHART = 'CHART',
  NAVIGATOR = 'NAVIGATOR',
  NAVIGATOR_PLOT_BASE = 'NAVIGATOR_PLOT_BASE'
}

export default ChartZones
